import { Flex, Heading } from '@chakra-ui/react'
import Container from '@/components/Container'
import React from 'react'
import Head from 'next/head'

const About = () => {
  return (
    <Container>
      <Head>
        <title>About - SpeakOut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex width='full' justify={'center'}>
        <Heading size="md">About Section</Heading>
      </Flex>
    </Container >
  )
}
export default About
