import Head from 'next/head'
import { Heading } from '@chakra-ui/react'
import Form from '../components/form.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>SpeakOut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
       <Form/>
     
    </>
  )
}
