import Head from 'next/head'
import Container from '@/components/Container.js'
import StoryForm from '@/components/StoryForm.js'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>SpeakOut</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoryForm />
    </Container>
    
  )
}
